### ISSUE TITLE
特定字符长度的时候遇到死循环或者截取范围超过的问题。请问怎么解决的？

### ISSUE THREAD

**Issue by cosyit** [lixp185/bookfx#3]
Hi，你好！当文本长度特定字符长度，比如说是 1066的时候，就会进入一个死循环的问题。请问这个问题是怎么回事啊。源码研究很久还是不怎么明白。[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (end): Invalid value: Not in inclusive range 713..1066: 1067
E/flutter (16639): #0      RangeError.checkValidRange (dart:core/errors.dart:379:9)
E/flutter (16639): #1      _StringBase.substring (dart:core-patch/string_patch.dart:398:27)
E/flutter (16639): #2      _EBookState.loadPages.<anonymous closure> (package:bookfx/src/e_book.dart:268:34)

**Comment by lixp185** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by cosyit** [comment]
我这边已经看懂代码了，问题解决了。谢谢您的分享。十分感谢！
